apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: youtube-ingress
spec:
  rules:
    - host: youtube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-ui-service
                port:
                  number: 80
          - path: /upload
            pathType: Prefix
            backend:
              service:
                name: uploader-service
                port:
                  number: 80
