apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
  namespace: youtube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
        - name: frontend-ui
          image: chandan669/frontend-ui:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ui-service
  namespace: youtube
spec:
  selector:
    app: frontend-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
