apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-uploader
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      containers:
        - name: uploader
          image: your-dockerhub/video-uploader:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: uploader-service
spec:
  selector:
    app: uploader
  ports:
    - port: 80
      targetPort: 8080
